[33m[nodemon] 1.19.4[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching dir(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:294
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:294:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:95
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:95:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:95
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:95:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:96
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:96:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:96
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:96:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:96
  getUsersAllpromise : getUsersAllpromise
                       ^

ReferenceError: getUsersAllpromise is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:96:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:2
console.log(__dir);
            ^

ReferenceError: __dir is not defined
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m

events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
(node:5) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
{}
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{}
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:3
console.log(db.);
               ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ username: [Function: validateUsername],
  password: [Function: validatePassword],
  email: [Function: validateEmail] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ username: [Function: validateUsername],
  password: [Function: validatePassword],
  email: [Function: validateEmail] }
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ username: [Function: validateUsername],
  password: [Function: validatePassword],
  email: [Function: validateEmail] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
{ query: [AsyncFunction: query],
  querypromise: [Function: querypromise] }
Listening on port 3000
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module './db_con'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/models/usersM.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/models/usersM.js:81
      result.records.forEach( (record) => arr.push(record.get('n') );
                                                                   ^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/app/nodeapp/app.js:43:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:93:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:75:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:75:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', userController.createUser(req, res));
                           ^

ReferenceError: userController is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:28)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:23
app.use( () => console.log('req recieved'););
                                         ^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', userController.createUser(req, res));
                           ^

ReferenceError: userController is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:28)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
(node:5) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:49
app.post(apiRoot+'users/', user.createUser(req, res));
                                           ^

ReferenceError: req is not defined
    at Object.<anonymous> (/app/nodeapp/app.js:49:44)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:56:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:59:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:59:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:59:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:59:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:60:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
req recieved
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:61:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:60:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:61:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:61:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:57:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:6
const app = express().Router();
                      ^

TypeError: express(...).Router is not a function
    at Object.<anonymous> (/app/nodeapp/app.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
catch err == TypeError: app.listen is not a function
[32m[nodemon] clean exit - waiting for changes before restart[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
catch err : TypeError: app.listen is not a function
[32m[nodemon] clean exit - waiting for changes before restart[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:15
app.use(express.json());                      // body-parse
    ^

TypeError: app.use is not a function
    at Object.<anonymous> (/app/nodeapp/app.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1395:7)
    at Function.listen (/app/nodeapp/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/app/nodeapp/app.js:58:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1286:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
Listening on port 3000
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:54
try {
    ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node nodeapp/app.js`[39m
/app/nodeapp/app.js:29
.get(function (req, res) =>)
                         ^^

SyntaxError: Unexpected token =>
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
